---
- hosts: work
  gather_facts: false
  tasks:
    - name: install ruby
      pacman:
        state: present
        update_cache: false
        name:
          - ruby
      become: true

    - name: load dummy data for stress testing
      # https://redis.io/topics/mass-insert
      shell: |
        /usr/bin/ruby <<EOF | redis-cli --pipe
        def gen_redis_proto(*cmd)
          proto = ""
          proto << "*"+cmd.length.to_s+"\r\n"
          cmd.each{|arg|
            proto << "$"+arg.to_s.bytesize.to_s+"\r\n"
            proto << arg.to_s+"\r\n"
          }
          proto
        end
        (0...1000000).each{|n|
          STDOUT.write(gen_redis_proto("SET","KEY#{n}","Value#{n}"))
        }
        EOF
