---
- name: setup redis cluster
  hosts: work
  gather_facts: true
  vars:
    ci: false
    latest: false
  tasks:
    - name: install packages
      pacman:
        state: present
        update_cache: true
        name:
          - redis
      become: true

    - name: disable binding
      lineinfile:
        path: /etc/redis.conf
        regexp: "^bind"
        line: "# bind"
      become: true

    - name: disable protected mode
      lineinfile:
        path: /etc/redis.conf
        regexp: "^protected-mode yes"
        line: "protected-mode no"
      become: true

    - name: specify the master
      lineinfile:
        path: /etc/redis.conf
        line: "slaveof {{ master_ip }} 6379"
      when: master is false
      become: true

    - name: sentinel configuration
      template:
        src: "templates/etc/{{ item }}.j2"
        dest: "/etc/{{ item }}"
        mode: 0644
        owner: root
        group: root
      with_items:
        - redis-sentinel.conf
      become: true

    - name: restart systemd services
      systemd: name={{ item }} enabled=true state=restarted
      with_items:
        - redis
      become: true
      when: not ci|bool
