---
- name: setup redis cluster
  hosts: work
  gather_facts: true
  vars:
    ci: false
    latest: false
  tasks:
    - name: install packages
      pacman:
        state: present
        update_cache: true
        name:
          - redis
      become: true

    - name: restart systemd services
      systemd: name={{ item }} enabled=true state=restarted
      with_items:
        - redis
      become: true
      when: not ci|bool
